### ISSUE TITLE
4.x zip file has an empty islandora_transforms folder

### ISSUE THREAD

**Issue by dchardin** [discoverygarden/basic-solr-config#199]
I thought it would be fine if I downloaded the zip file, but I have found that the islandora_transforms folder is empty, so when I followed the solr installation instructions, things didn't turn out very well for my solr setup. Can someone set up the hosted zip file to always mirror the git repo?

**Comment by willtp87** [comment]
The zip file I believe you are referring to is generated by github, and while it does mirror the git repo it is not the recommended installation procedure.  Instructions are linked in the README.md. I believe you may be missing the [library](https://github.com/discoverygarden/islandora_transforms). I don't believe we will be moving to formal release procedures for this repo yet.
