### ISSUE TITLE
demoOnSolr

### ISSUE THREAD

**Issue by DannyJoris** [discoverygarden/basic-solr-config#2]
Just a thought, but should we start using another schema name? Something better than 'demoOnSolr'. Drupal uses 'drupal-3.0-beta14-solr3' for example, which is a bit more meaningful. Drupal also uses the 'example' solr setup, so it should be possible.

Maybe 'islandora-solr-1.4' ?

**Comment by willtp87** [comment]
This repo is meant as a drop in replacement for installs that follow the Islandora installation guide. Your suggestion has merit, but maybe a documentation change request should go through the Jira system.

**Comment by DannyJoris** [comment]
I see. In that case, maybe we can include these files with the islandora solr module and have them copied over to the solr instance on installation. This is how the drupal Apachesolr module does it too. That could simplify at least some steps in the documentation. I'll post this into Jira as well.

**Comment by DannyJoris** [comment]
I just noticed that there are a few files included, but do we ever use those? https://github.com/Islandora/islandora_solr_search/tree/6.x/solr_xmls

**Comment by willtp87** [comment]
They have often formed the basis for the Solr configuration in our projects.  It has always needed to be highly modified though.  This repo is meant to be a more sustainable and easily configurable solution, but is not ready for distribution.  I'd be happy to discuss the rationale in the office.
